# Generated by Django 3.2 on 2021-04-12 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='DepartmentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalysisApp.team'),
        ),
    ]
