# Generated by Django 3.2 on 2021-04-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisApp', '0003_auto_20210412_1227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
