# Generated by Django 3.2 on 2021-04-28 08:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisApp', '0004_rename_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polen',
            fields=[
                ('AnalysisId', models.AutoField(primary_key=True, serialize=False)),
                ('AnalysisName', models.CharField(max_length=100)),
                ('AnalysisDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('SampleDate', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=100)),
                ('PhotoFilePath', models.CharField(max_length=100)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalysisApp.user')),
            ],
        ),
    ]
