# Generated by Django 3.2 on 2021-04-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisApp', '0005_polen'),
    ]

    operations = [
        migrations.AddField(
            model_name='polen',
            name='AnalysisResult',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='polen',
            name='PhotoFileName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='polen',
            name='PhotoFilePath',
            field=models.CharField(max_length=200),
        ),
    ]
