# Generated by Django 3.2 on 2021-04-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisApp', '0006_auto_20210428_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polen',
            name='AnalysisDate',
            field=models.DateField(),
        ),
    ]
