# Generated by Django 3.2 on 2021-05-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisApp', '0007_alter_polen_analysisdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolinicRanges',
            fields=[
                ('DateOfStart', models.DateField(primary_key=True, serialize=False)),
                ('DateOfEnd', models.DateField(unique=True)),
                ('TypeOfPolen1', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
