# Generated by Django 3.2 on 2021-05-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisApp', '0008_polinicranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='polinicranges',
            name='RangeId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='polinicranges',
            name='DateOfStart',
            field=models.DateField(unique=True),
        ),
    ]
