# Generated by Django 3.2 on 2021-05-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisApp', '0009_auto_20210505_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polinicranges',
            name='TypeOfPolen1',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
