# Generated by Django 3.2 on 2021-05-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisApp', '0010_alter_polinicranges_typeofpolen1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polinicranges',
            name='TypeOfPolen1',
            field=models.IntegerField(),
        ),
    ]
