# Generated by Django 3.2 on 2021-05-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisApp', '0011_alter_polinicranges_typeofpolen1'),
    ]

    operations = [
        migrations.AddField(
            model_name='polen',
            name='AnalysisResult2',
            field=models.IntegerField(default=0),
        ),
    ]
