# Generated by Django 3.2 on 2021-05-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisApp', '0012_polen_analysisresult2'),
    ]

    operations = [
        migrations.AddField(
            model_name='polinicranges',
            name='TypeOfPolen10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polinicranges',
            name='TypeOfPolen11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polinicranges',
            name='TypeOfPolen12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polinicranges',
            name='TypeOfPolen2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polinicranges',
            name='TypeOfPolen3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polinicranges',
            name='TypeOfPolen4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polinicranges',
            name='TypeOfPolen5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polinicranges',
            name='TypeOfPolen6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polinicranges',
            name='TypeOfPolen7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polinicranges',
            name='TypeOfPolen8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polinicranges',
            name='TypeOfPolen9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='polinicranges',
            name='TypeOfPolen1',
            field=models.IntegerField(default=0),
        ),
    ]
