# Generated by Django 3.2 on 2021-05-17 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AnalysisApp', '0013_auto_20210506_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='TeamId',
        ),
        migrations.AlterField(
            model_name='polen',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
