# Generated by Django 3.2 on 2021-05-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisApp', '0015_polinicranges_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polinicranges',
            name='DateOfEnd',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='polinicranges',
            name='DateOfStart',
            field=models.DateField(),
        ),
    ]
