# Generated by Django 3.2 on 2021-06-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisApp', '0016_auto_20210517_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolenType',
            fields=[
                ('PolenId', models.AutoField(primary_key=True, serialize=False)),
                ('PolenTypeName', models.CharField(max_length=100)),
                ('BiologicalName', models.CharField(max_length=200)),
            ],
        ),
    ]
