# Generated by Django 3.2 on 2021-06-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisApp', '0017_polentype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polentype',
            old_name='BiologicalName',
            new_name='Biological_Name',
        ),
        migrations.RenameField(
            model_name='polentype',
            old_name='PolenTypeName',
            new_name='Polen_Type_Name',
        ),
    ]
