# Generated by Django 3.2 on 2021-06-01 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisApp', '0018_auto_20210601_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolenPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Percentage', models.IntegerField(default=0)),
                ('PolenTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalysisApp.polentype')),
                ('PolinicRangesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalysisApp.polinicranges')),
            ],
        ),
    ]
