# Generated by Django 3.2 on 2021-06-02 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisApp', '0019_polenpercentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polinicranges',
            name='TypeOfPolen1',
        ),
        migrations.RemoveField(
            model_name='polinicranges',
            name='TypeOfPolen10',
        ),
        migrations.RemoveField(
            model_name='polinicranges',
            name='TypeOfPolen11',
        ),
        migrations.RemoveField(
            model_name='polinicranges',
            name='TypeOfPolen12',
        ),
        migrations.RemoveField(
            model_name='polinicranges',
            name='TypeOfPolen2',
        ),
        migrations.RemoveField(
            model_name='polinicranges',
            name='TypeOfPolen3',
        ),
        migrations.RemoveField(
            model_name='polinicranges',
            name='TypeOfPolen4',
        ),
        migrations.RemoveField(
            model_name='polinicranges',
            name='TypeOfPolen5',
        ),
        migrations.RemoveField(
            model_name='polinicranges',
            name='TypeOfPolen6',
        ),
        migrations.RemoveField(
            model_name='polinicranges',
            name='TypeOfPolen7',
        ),
        migrations.RemoveField(
            model_name='polinicranges',
            name='TypeOfPolen8',
        ),
        migrations.RemoveField(
            model_name='polinicranges',
            name='TypeOfPolen9',
        ),
    ]
